export type LanguageCode = "en" | "fr" | "es" | "ar" | "sw" | "ha" | "yo" | "ig";
export type CurrencyCode = "NGN" | "USD" | "EUR" | "GBP" | "KES" | "GHS";

export interface CurrencyDetails {
  symbol: string;
  rate: number; // 1 NGN = Rate in Target Currency
  name: string;
}

export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "sw", name: "Kiswahili", flag: "🇰🇪" },
  { code: "ha", name: "Hausa", flag: "🇳🇬" },
  { code: "yo", name: "Yoruba", flag: "🇳🇬" },
  { code: "ig", name: "Igbo", flag: "🇳🇬" },
];

export const SUPPORTED_CURRENCIES: Record<CurrencyCode, CurrencyDetails> = {
  NGN: { symbol: "₦", rate: 1.0, name: "Naira" },
  USD: { symbol: "$", rate: 1 / 1500, name: "US Dollar" },
  EUR: { symbol: "€", rate: 1 / 1600, name: "Euro" },
  GBP: { symbol: "£", rate: 1 / 1900, name: "British Pound" },
  KES: { symbol: "KSh", rate: 1 / 12, name: "Kenyan Shilling" },
  GHS: { symbol: "GH₵", rate: 1 / 100, name: "Ghanaian Cedi" },
};

// Simple, curated translations dictionary for worldwide accessibility
export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {}, // Default fallback
  fr: {
    "Home": "Accueil",
    "Earn": "Gagner",
    "Offers": "Offres",
    "Wallet": "Portefeuille",
    "Me": "Profil",
    "Available Wallet Balance": "Solde de portefeuille disponible",
    "Available Payout Pocket": "Poche de paiement disponible",
    "Pending Escrow": "Escrow en attente",
    "Referral Earned": "Parrainage gagné",
    "Bonus Balance": "Solde bonus",
    "Cash Out": "Retirer de l'argent",
    "Secure Transfer": "Transfert sécurisé",
    "Bill Payments": "Paiement de factures",
    "Lucky Wheel": "Roue de la chance",
    "Sponsor Ad": "Publicité sponsorisée",
    "Hot Deals": "Offres chaudes",
    "Complete tasks": "Accomplir les tâches",
    "Upgrade Account": "Mettre à niveau le compte",
    "Verify KYC": "Vérifier le KYC",
    "Dashboard": "Tableau de bord",
    "Advertiser Console": "Console de l'annonceur",
    "Admin Panel": "Panneau d'administration",
    "Submit Verification": "Soumettre la vérification",
    "Pending": "En attente",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "Active Campaigns": "Campagnes actives",
    "Total Budget": "Budget total",
    "Tasks Limit": "Limite de tâches",
    "Role active": "Rôle actif",
    "Open Console": "Ouvrir la console",
    "Open Admin": "Ouvrir l'administration",
    "Logout": "Se déconnecter",
    "Welcome to EarnPay": "Bienvenue sur EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "La plateforme professionnelle de récompenses fintech d'entreprise pour les utilisateurs et annonceurs mondiaux.",
    "Email or Phone Number": "E-mail ou numéro de téléphone",
    "Legal Full Name": "Nom complet légal",
    "Enter Password Hash": "Entrez le mot de passe",
    "Account Profile Type": "Type de profil de compte",
    "Earner / User": "Gagneur / Utilisateur",
    "Advertiser": "Annonceur",
    "Unleash Client account nodes": "Libérer les comptes clients",
    "Login Securely": "Connexion sécurisée",
    "Access Personal Wallet": "Accéder au portefeuille personnel",
    "Complete Register & Onboard": "Terminer l'inscription",
    "Have an account? Login here": "Vous avez un compte ? Connectez-vous ici",
    "Don't have an account? Sign up here": "Pas de compte ? Inscrivez-vous ici",
    "Demonstration Access Accounts": "Comptes d'accès de démonstration",
    "EarnPay stores persistent states in `db-store.json`. Reviewers can login with mock accounts above, or register fresh nodes to try out the system!": "EarnPay stocke les états persistants dans `db-store.json`. Les examinateurs peuvent se connecter avec les comptes ci-dessus !",
    "Upgrade & Amplify Earnings": "Mettre à niveau les gains",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "Mettez à niveau votre niveau d'adhésion pour débloquer de meilleurs tarifs de gains."
  },
  es: {
    "Home": "Inicio",
    "Earn": "Ganar",
    "Offers": "Ofertas",
    "Wallet": "Cartera",
    "Me": "Perfil",
    "Available Wallet Balance": "Saldo disponible de la cartera",
    "Available Payout Pocket": "Bolsillo de pago disponible",
    "Pending Escrow": "Escrow en espera",
    "Referral Earned": "Referido ganado",
    "Bonus Balance": "Saldo de bonificación",
    "Cash Out": "Retirar fondos",
    "Secure Transfer": "Transferencia segura",
    "Bill Payments": "Pagos de facturas",
    "Lucky Wheel": "Rueda de la suerte",
    "Sponsor Ad": "Anuncio patrocinado",
    "Hot Deals": "Ofertas calientes",
    "Complete tasks": "Completar tareas",
    "Upgrade Account": "Actualizar cuenta",
    "Verify KYC": "Verificar KYC",
    "Dashboard": "Tablero de mandos",
    "Advertiser Console": "Consola del anunciante",
    "Admin Panel": "Panel de administración",
    "Submit Verification": "Enviar verificación",
    "Pending": "Pendiente",
    "Approved": "Aprobado",
    "Rejected": "Rechazado",
    "Active Campaigns": "Campañas activas",
    "Total Budget": "Presupuesto total",
    "Tasks Limit": "Límite de tareas",
    "Role active": "Rol activo",
    "Open Console": "Abrir consola",
    "Open Admin": "Abrir administración",
    "Logout": "Cerrar sesión",
    "Welcome to EarnPay": "Bienvenido a EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "La plataforma profesional de recompensas de tecnología financiera para usuarios y anunciantes del mundo.",
    "Email or Phone Number": "Correo electrónico o número de teléfono",
    "Legal Full Name": "Nombre legal completo",
    "Enter Password Hash": "Introducir contraseña",
    "Account Profile Type": "Tipo de perfil de cuenta",
    "Earner / User": "Ganador / Usuario",
    "Advertiser": "Anunciante",
    "Unleash Client account nodes": "Desbloquear cuentas de clientes",
    "Login Securely": "Iniciar sesión de forma segura",
    "Access Personal Wallet": "Acceder a cartera personal",
    "Complete Register & Onboard": "Completar registro",
    "Have an account? Login here": "¿Tiene una cuenta? Inicie sesión aquí",
    "Don't have an account? Sign up here": "¿No tiene una cuenta? Regístrese aquí",
    "Demonstration Access Accounts": "Nodos de acceso al simulador de prueba",
    "Upgrade & Amplify Earnings": "Actualizar y ampliar ganancias",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "Actualice su nivel de membresía para desbloquear mayores límites de retiro."
  },
  ar: {
    "Home": "الرئيسية",
    "Earn": "كسب",
    "Offers": "العروض",
    "Wallet": "المحفظة",
    "Me": "حسابي",
    "Available Wallet Balance": "رصيد المحفظة المتاح",
    "Available Payout Pocket": "جيب الصرف المتاح",
    "Pending Escrow": "الضمان المعلق",
    "Referral Earned": "أرباح الإحالة",
    "Bonus Balance": "رصيد المكافأة",
    "Cash Out": "صرف النقود",
    "Secure Transfer": "تحويل آمن",
    "Bill Payments": "دفع الفواتير",
    "Lucky Wheel": "عجلة الحظ",
    "Sponsor Ad": "إعلان ممول",
    "Hot Deals": "صفقات ساخنة",
    "Complete tasks": "إكمال المهام",
    "Upgrade Account": "ترقية الحساب",
    "Verify KYC": "توثيق الهوية",
    "Dashboard": "لوحة التحكم",
    "Advertiser Console": "لوحة المعلنين",
    "Admin Panel": "لوحة الإدارة",
    "Submit Verification": "تقديم التحقق",
    "Pending": "قيد الانتظار",
    "Approved": "تمت الموافقة",
    "Rejected": "مرفوض",
    "Active Campaigns": "الحملات النشطة",
    "Total Budget": "الميزانية الإجمالية",
    "Tasks Limit": "حد المهام",
    "Role active": "الدور النشط",
    "Open Console": "افتح لوحة المعلن",
    "Open Admin": "افتح لوحة الإدارة",
    "Logout": "تسجيل الخروج",
    "Welcome to EarnPay": "مرحباً بكم في EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "منصة المكافآت المالية والمهنية للمستخدمين والمعلنين في جميع أنحاء العالم.",
    "Email or Phone Number": "البريد الإلكتروني أو رقم الهاتف",
    "Legal Full Name": "الاسم الكامل القانوني",
    "Enter Password Hash": "أدخل كلمة المرور",
    "Account Profile Type": "نوع ملف الحساب",
    "Earner / User": "الكاسب / المستخدم",
    "Advertiser": "المعلن",
    "Unleash Client account nodes": "إطلاق حساب العميل",
    "Login Securely": "تسجيل الدخول بأمان",
    "Access Personal Wallet": "الوصول إلى المحفظة الشخصية",
    "Complete Register & Onboard": "إكمال التسجيل والانضمام",
    "Have an account? Login here": "هل لديك حساب؟ سجل الدخول هنا",
    "Don't have an account? Sign up here": "ليس لديك حساب؟ سجل معنا هنا",
    "Upgrade & Amplify Earnings": "ترقية وزيادة الأرباح",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "قم بترقية مستوى العضوية للوصول إلى مكافآت أعلى ومعالجة ذات أولوية وخيارات المهام اليومية."
  },
  sw: {
    "Home": "Nyumbani",
    "Earn": "Pata Kazi",
    "Offers": "Ofa",
    "Wallet": "Miliki",
    "Me": "Mimi",
    "Available Wallet Balance": "Salio la Pochi linalopatikana",
    "Available Payout Pocket": "Mfuko wa kufuta malipo",
    "Pending Escrow": "Dhamana Inayosubiri",
    "Referral Earned": "Mapato ya Rufaa",
    "Bonus Balance": "Salio la Bonasi",
    "Cash Out": "Toa Pesa",
    "Secure Transfer": "Uhamisho Salama",
    "Bill Payments": "Malipo ya Huduma",
    "Lucky Wheel": "Gurudumu la Bahati",
    "Sponsor Ad": "Tangazo la Mdhamini",
    "Hot Deals": "Ofa Moto",
    "Complete tasks": "Kamilisha kazi",
    "Upgrade Account": "Boresha Akaunti",
    "Verify KYC": "Thibitisha KYC",
    "Dashboard": "Kipengele",
    "Advertiser Console": "Dashibodi ya Mtangazaji",
    "Admin Panel": "Dashibodi ya Wasimamizi",
    "Submit Verification": "Wasilisha Uhakiki",
    "Pending": "Inasubiri",
    "Approved": "Imeidhinishwa",
    "Rejected": "Imekataliwa",
    "Active Campaigns": "Kampeni Zinazoendelea",
    "Total Budget": "Makisio ya Bajeti",
    "Tasks Limit": "Kikomo cha Kazi",
    "Role active": "Jukumu linafanya kazi",
    "Open Console": "Fungua Dashibodi",
    "Open Admin": "Fungua Usimamizi",
    "Logout": "Ondoka",
    "Welcome to EarnPay": "Karibu kwenye EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "Jukwaa la kitaalamu la zawadi za teknolojia ya kifedha kwa watumiaji na watangazaji ulimwenguni kote.",
    "Email or Phone Number": "Barua Pepe au Nambari ya Simu",
    "Legal Full Name": "Majina Kamili ya Kisheria",
    "Enter Password Hash": "Weka Nenosiri",
    "Account Profile Type": "Aina ya Wasifu",
    "Earner / User": "Mtafutaji / Mtumiaji",
    "Advertiser": "Mtangazaji",
    "Unleash Client account nodes": "Sanidi Akaunti",
    "Login Securely": "Ingia kwa Salaama",
    "Access Personal Wallet": "Fikia Mkoba wa Binafsi",
    "Complete Register & Onboard": "Kamilisha Usajili",
    "Have an account? Login here": "Je, una akaunti? Ingia hapa",
    "Don't have an account? Sign up here": "Huna akaunti? Jisajili sasa",
    "Upgrade & Amplify Earnings": "Boresha na Kuza Mapato",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "Boresha daraja la uanachama ili kuongeza uwezo wa kutoa pesa."
  },
  ha: {
    "Home": "Gida",
    "Earn": "Neman Kudi",
    "Offers": "Tayi na Musamman",
    "Wallet": "Asusu",
    "Me": "Suna na Hoto",
    "Available Wallet Balance": "Asusunka na Kudi da zaka iya cirewa",
    "Available Payout Pocket": "Kundin Cire Kudi",
    "Pending Escrow": "Kudaden da aka riqe",
    "Referral Earned": "Kudin Gayyata",
    "Bonus Balance": "Kudin Kyauta",
    "Cash Out": "Cire Kudi",
    "Secure Transfer": "Tura Kudi cikin Aminci",
    "Bill Payments": "Biyan Kudade / Cajin Kati",
    "Lucky Wheel": "Tafarnuwa Mai Sa'a",
    "Sponsor Ad": "Tallan Abokin Hulda",
    "Hot Deals": "Zafafan Tayi na Musamman",
    "Complete tasks": "Cika aikoni don samun kudi",
    "Upgrade Account": "Inganta Matsayin Asusu",
    "Verify KYC": "Tabbatar da Shaidarka",
    "Dashboard": "Shafin Gudanarwa",
    "Advertiser Console": "Shafin Tallace-tallace",
    "Admin Panel": "Gidan Admin",
    "Submit Verification": "Tura Shawara",
    "Pending": "Ana Dubawa",
    "Approved": "An amince dashi",
    "Rejected": "An ki amincewa",
    "Active Campaigns": "Tallace-tallace da ke aiki yanzu",
    "Total Budget": "Adadin Kudin Talla",
    "Tasks Limit": "Iyakacin Ayyukan Rana",
    "Role active": "Rol dinka",
    "Open Console": "Bude Console",
    "Open Admin": "Bude Admin",
    "Logout": "Fita Daga Asusu",
    "Welcome to EarnPay": "Barka da Zuwa EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "Babban dandamali na musamman don samun kudi da gudanar da tallace-tallace a fadin duniya baki daya.",
    "Email or Phone Number": "Imel ko Lambar Waya",
    "Legal Full Name": "Cikakken Sunanka na Gaskiya",
    "Enter Password Hash": "Shigar da Lambar Tsaro (Password)",
    "Account Profile Type": "Nau'in Asusu",
    "Earner / User": "Mai Neman Kudi (Earner)",
    "Advertiser": "Mai Tallata Kaya",
    "Unleash Client account nodes": "Kaddamar da Sabon Asusu",
    "Login Securely": "Shiga cikin Aminci",
    "Access Personal Wallet": "Koma Kan Aljihun Kudi",
    "Complete Register & Onboard": "Kammala Rajista",
    "Have an account? Login here": "Kuna da asusu riga? Shiga nan",
    "Don't have an account? Sign up here": "Baku da asusu? Yi rajista nan",
    "Upgrade & Amplify Earnings": "Inganta Matsayin samun kudi",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "Inganta asusunku don samun ikon janye kudi da samun ayyuka barkatai."
  },
  yo: {
    "Home": "Ile",
    "Earn": "Gba Owo",
    "Offers": "Ipese",
    "Wallet": "Apamọwọ",
    "Me": "Emi",
    "Available Wallet Balance": "Owo to wa ninu apamọwọ rẹ",
    "Available Payout Pocket": "Apo sisan owo rẹ",
    "Pending Escrow": "Owo ti a dusi lọwọ",
    "Referral Earned": "Owo igbanisiṣẹ ti o gba",
    "Bonus Balance": "Owo ajẹmọnu",
    "Cash Out": "Gba Owo rẹ",
    "Secure Transfer": "Gbe owo lọna rọrun ko si jamba",
    "Bill Payments": "Sisan owo ina ati omi",
    "Lucky Wheel": "Kẹkẹ Oriire",
    "Sponsor Ad": "Tala Olugbowo",
    "Hot Deals": "Awọn Ipese to gbona gidi",
    "Complete tasks": "Kọ awọn iṣẹ lati gba owo ṣiṣẹ",
    "Upgrade Account": "Amúgbòòrò Akọọlẹ",
    "Verify KYC": "Fi Idanimọ rẹ mulẹ",
    "Dashboard": "Tabili Oludari",
    "Advertiser Console": "Agbegbe Awọn ti o n polowo",
    "Admin Panel": "Agbegbe Oludari Platform",
    "Submit Verification": "Fi idanimọ ranṣẹ",
    "Pending": "O n bọ lọna",
    "Approved": "A ti fọwọsi",
    "Rejected": "A kọ owo rẹ",
    "Active Campaigns": "Awọn Talla ti n lọ lọwọ",
    "Total Budget": "Gbogbo Owo Talla",
    "Tasks Limit": "Iye iṣẹ fun ọjọ kan",
    "Role active": "Ipa t'o n ṣiṣẹ lọwọ",
    "Open Console": "Ṣi Agbegbe rẹ",
    "Open Admin": "Ṣi Tabili Oludari",
    "Logout": "Bọ kuro ni akọọlẹ rẹ",
    "Welcome to EarnPay": "Kaabo si EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "Syeed fintech ti o ni aabo fun awọn ti n gba owo ati awọn ti n polowo ni gbogbo agbaye.",
    "Email or Phone Number": "Imeeli tabi Nọmba Waya",
    "Legal Full Name": "Orukọ Kikun rẹ ti Ofin",
    "Enter Password Hash": "Tẹ nọmba aabo rẹ",
    "Account Profile Type": "Iru Apoṣiṣẹ ti o fẹ da",
    "Earner / User": "Ẹni to n gba owo (User)",
    "Advertiser": "Ẹni to n polowo ọjà",
    "Unleash Client account nodes": "Ṣe ifilọlẹ akọọlẹ rẹ",
    "Login Securely": "Wọle lọna aabo",
    "Access Personal Wallet": "Wọle si Apamọwọ rẹ",
    "Complete Register & Onboard": "Kọ orukọ rẹ de opin",
    "Have an account? Login here": "Ti o ba ti ni akọọlẹ? Wọle nihin",
    "Don't have an account? Sign up here": "Ini akọọlẹ kankan? Forukọsilẹ nihin",
    "Upgrade & Amplify Earnings": "Igbega Akọọlẹ rẹ",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "Ṣe igbega akọọlẹ rẹ ki o ba le gba owo pupọ ati cire wọn."
  },
  ig: {
    "Home": "Ụlọ",
    "Earn": "Nweta Ego",
    "Offers": "Onyinye nkwado",
    "Wallet": "Akpa Ego",
    "Me": "Kem",
    "Available Wallet Balance": "Ego dị n'akpa gị ugbu a",
    "Available Payout Pocket": "Akpa ego mwepụ",
    "Pending Escrow": "Ego a tụrụ n'ụlọ mkpọrọ",
    "Referral Earned": "Ego ịkpọ mmadụ n'ụlọ",
    "Bonus Balance": "Ego bonus gị",
    "Cash Out": "Kpatara ego gị",
    "Secure Transfer": "Ziga ego na nchekwa",
    "Bill Payments": "Ịkwụ ụgwọ mmiri na ọkụ",
    "Lucky Wheel": "Wheel nke kechi",
    "Sponsor Ad": "Ad nkwado",
    "Hot Deals": "Nnukwu Onyinye ugbu a",
    "Complete tasks": "Rụọ ọrụ nweta ego",
    "Upgrade Account": "Nye akpa gị nkwalite",
    "Verify KYC": "Kwapụta njirimara gị",
    "Dashboard": "Ebe Nchịkwa",
    "Advertiser Console": "Console ndị nkwado",
    "Admin Panel": "Ebe Admin",
    "Submit Verification": "Nyefee nkwenye gị",
    "Pending": "Na-eche nkwado",
    "Approved": "A kwadoro ya",
    "Rejected": "A jụrụ ya",
    "Active Campaigns": "Ad na-arụ ọrụ ugbu a",
    "Total Budget": "Budget nile",
    "Tasks Limit": "Mkpọsa ọrụ gị na mbụ",
    "Role active": "Ọkwa gị ugbu a",
    "Open Console": "Mepee console gị",
    "Open Admin": "Mepee ebe admin",
    "Logout": "Pụọ n'asusu",
    "Welcome to EarnPay": "Nnọọ na EarnPay",
    "The professional enterprise fintech rewards platform for world wide users and advertisers.": "Igbe nkwado fintech maka ndị niile na-arụ ọrụ na ndị nkwado n'ọkwa ụwa niile.",
    "Email or Phone Number": "E-mail ma ọ bụ nọmba ekwentị gị",
    "Legal Full Name": "Aha gị zuru oke na iwu",
    "Enter Password Hash": "Tinye paswọdu gị",
    "Account Profile Type": "Ụdị akaụntụ ị chọrọ",
    "Earner / User": "Onye na-arụ ọrụ (Earner)",
    "Advertiser": "Onye na-akpọsa ad",
    "Unleash Client account nodes": "Bido akaụntụ gị",
    "Login Securely": "Banye na nchekwa",
    "Access Personal Wallet": "Gaa na akpa ego gị",
    "Complete Register & Onboard": "Kụọ aha gị n'akwụkwọ nile",
    "Have an account? Login here": "Ị nwere akaụntụ? Banye ebe a",
    "Don't have an account? Sign up here": "Ị nweghị akaụntụ ugbu a? Debanye aha ebe a",
    "Upgrade & Amplify Earnings": "Mee ka akpa gị nwee ume",
    "Upgrade membership tier level to access higher rewards, priority processing, and daily task options.": "Nwee nkwalite ọkwa ka ị kpata ego buru ibu ma dọpụta ya."
  }
};

// Global translation lookup helper that also translates common phrases dynamically
export function translateText(text: string, lang: LanguageCode): string {
  if (lang === "en") return text;
  
  const dict = TRANSLATIONS[lang];
  if (!dict) return text;
  
  // Try exact match
  if (dict[text]) return dict[text];
  
  // Try case-insensitive or trimmed match
  const trimmed = text.trim();
  if (dict[trimmed]) return dict[trimmed];

  // Try direct replacement of sentences
  for (const [key, val] of Object.entries(dict)) {
    if (trimmed.toLowerCase().includes(key.toLowerCase())) {
      return val;
    }
  }

  return text;
}
